language: node_js
node_js:
  - 7
  - 8

jobs:
  include:
    - stage: deploy
      node_js: "8"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 'silva20102@gmail.com'
        api_key: $NMP_API_KEY
        on: master


